baseURL = "https://mondaiya.github.io/"
title = "問題屋"
theme = "HugoTeX"
paginate = 3
languageCode = "zh-TW"
DefaultContentLanguage = "zh-TW"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[author]
abstract = "優雅的數位化習題集"

[taxonomies]
category = "目錄"
tag = "標籤"
series = "系列"